spring.datasource.url=jdbc:mysql://localhost/vollmed_api
spring.datasource.username=root
spring.datasource.password=root

# Habilitando Logs de SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Quando der erro em algum enpoint, não retorna o stacktrace
spring.web.error.include-stacktrace=never

# Configurando chave para codificacção do token
# "JWT_SECRET" é uma variavel configurada no sistema operacional, para desenvolvimento local ou
# para quando ela não estiver configurada, sera usada a senha "12345678" como default
api.security.token.secret=${JWT_SECRET:12345678}
